"""empty message

Revision ID: 1266c15ac0ba
Revises: b7a62dd96edb
Create Date: 2020-10-08 21:59:17.838672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1266c15ac0ba'
down_revision = 'b7a62dd96edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_day_of_month', table_name='request')
    op.drop_index('ix_request_end_time', table_name='request')
    op.drop_index('ix_request_start_time', table_name='request')
    op.drop_column('request', 'day_of_month')
    op.drop_column('request', 'end_time')
    op.drop_column('request', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('start_time', sa.INTEGER(), nullable=True))
    op.add_column('request', sa.Column('end_time', sa.INTEGER(), nullable=True))
    op.add_column('request', sa.Column('day_of_month', sa.INTEGER(), nullable=True))
    op.create_index('ix_request_start_time', 'request', ['start_time'], unique=False)
    op.create_index('ix_request_end_time', 'request', ['end_time'], unique=False)
    op.create_index('ix_request_day_of_month', 'request', ['day_of_month'], unique=False)
    # ### end Alembic commands ###
