"""added priorities

Revision ID: 2b0b5c507909
Revises: 85a21c502796
Create Date: 2020-10-27 13:54:40.989275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0b5c507909'
down_revision = '85a21c502796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')
        batch_op.drop_column('day_of_month')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_month', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
