"""empty message

Revision ID: 718bc4d05640
Revises: 
Create Date: 2020-10-08 14:54:10.054740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718bc4d05640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('facility', sa.String(length=64), nullable=True),
    sa.Column('is_integrator', sa.Boolean(), nullable=True),
    sa.Column('is_facility_admin', sa.Boolean(), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=28), nullable=True),
    sa.Column('lname', sa.String(length=28), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_company'), 'user', ['company'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_facility'), 'user', ['facility'], unique=False)
    op.create_index(op.f('ix_user_fname'), 'user', ['fname'], unique=False)
    op.create_index(op.f('ix_user_lname'), 'user', ['lname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('beam', sa.String(length=16), nullable=True),
    sa.Column('ion', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('fluence', sa.Integer(), nullable=True),
    sa.Column('flux', sa.Integer(), nullable=True),
    sa.Column('LET', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('beam_size', sa.Integer(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_LET'), 'request', ['LET'], unique=False)
    op.create_index(op.f('ix_request_beam'), 'request', ['beam'], unique=False)
    op.create_index(op.f('ix_request_beam_size'), 'request', ['beam_size'], unique=False)
    op.create_index(op.f('ix_request_energy'), 'request', ['energy'], unique=False)
    op.create_index(op.f('ix_request_facility'), 'request', ['facility'], unique=False)
    op.create_index(op.f('ix_request_fluence'), 'request', ['fluence'], unique=False)
    op.create_index(op.f('ix_request_flux'), 'request', ['flux'], unique=False)
    op.create_index(op.f('ix_request_hours'), 'request', ['hours'], unique=False)
    op.create_index(op.f('ix_request_ion'), 'request', ['ion'], unique=False)
    op.create_index(op.f('ix_request_status'), 'request', ['status'], unique=False)
    op.create_index(op.f('ix_request_user_id'), 'request', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_user_id'), table_name='request')
    op.drop_index(op.f('ix_request_status'), table_name='request')
    op.drop_index(op.f('ix_request_ion'), table_name='request')
    op.drop_index(op.f('ix_request_hours'), table_name='request')
    op.drop_index(op.f('ix_request_flux'), table_name='request')
    op.drop_index(op.f('ix_request_fluence'), table_name='request')
    op.drop_index(op.f('ix_request_facility'), table_name='request')
    op.drop_index(op.f('ix_request_energy'), table_name='request')
    op.drop_index(op.f('ix_request_beam_size'), table_name='request')
    op.drop_index(op.f('ix_request_beam'), table_name='request')
    op.drop_index(op.f('ix_request_LET'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_lname'), table_name='user')
    op.drop_index(op.f('ix_user_fname'), table_name='user')
    op.drop_index(op.f('ix_user_facility'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_company'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
