"""fixed DateTime error

Revision ID: 737952672a25
Revises: 2b0b5c507909
Create Date: 2021-03-05 15:08:44.400699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737952672a25'
down_revision = '2b0b5c507909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_splittable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('range', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shifts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('split', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stale', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_request_is_splittable'), ['is_splittable'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_range'), ['range'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_shifts'), ['shifts'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_split'), ['split'], unique=False)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('day_of_month')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_month', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_request_split'))
        batch_op.drop_index(batch_op.f('ix_request_shifts'))
        batch_op.drop_index(batch_op.f('ix_request_range'))
        batch_op.drop_index(batch_op.f('ix_request_is_splittable'))
        batch_op.drop_column('stale')
        batch_op.drop_column('split')
        batch_op.drop_column('shifts')
        batch_op.drop_column('range')
        batch_op.drop_column('priority')
        batch_op.drop_column('is_splittable')

    # ### end Alembic commands ###
