"""empty message

Revision ID: b7a62dd96edb
Revises: 1446d45a4f67
Create Date: 2020-10-08 21:37:32.028828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a62dd96edb'
down_revision = '1446d45a4f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_is_maintenance', table_name='request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_request_is_maintenance', 'request', ['is_maintenance'], unique=False)
    # ### end Alembic commands ###
