"""empty message

Revision ID: cfeff16638c2
Revises: 1266c15ac0ba
Create Date: 2020-10-21 15:22:02.271477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfeff16638c2'
down_revision = '1266c15ac0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('is_splittable', sa.Boolean(), nullable=True))
    op.add_column('request', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('range', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('shifts', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('split', sa.Boolean(), nullable=True))
    op.add_column('request', sa.Column('stale', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_request_is_splittable'), 'request', ['is_splittable'], unique=False)
    op.create_index(op.f('ix_request_range'), 'request', ['range'], unique=False)
    op.create_index(op.f('ix_request_shifts'), 'request', ['shifts'], unique=False)
    op.create_index(op.f('ix_request_split'), 'request', ['split'], unique=False)
    op.drop_column('request', 'start_time')
    op.drop_column('request', 'end_time')
    op.drop_column('request', 'day_of_month')
    op.add_column('user', sa.Column('priority', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'priority')
    op.add_column('request', sa.Column('day_of_month', sa.INTEGER(), nullable=True))
    op.add_column('request', sa.Column('end_time', sa.INTEGER(), nullable=True))
    op.add_column('request', sa.Column('start_time', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_request_split'), table_name='request')
    op.drop_index(op.f('ix_request_shifts'), table_name='request')
    op.drop_index(op.f('ix_request_range'), table_name='request')
    op.drop_index(op.f('ix_request_is_splittable'), table_name='request')
    op.drop_column('request', 'stale')
    op.drop_column('request', 'split')
    op.drop_column('request', 'shifts')
    op.drop_column('request', 'range')
    op.drop_column('request', 'priority')
    op.drop_column('request', 'is_splittable')
    # ### end Alembic commands ###
